# use c and gcc
language: c
compiler: gcc

# only build branches on whitelist
#branches:
#  only:
#    - setup-ci

# install dependencies
before_install:
  - sudo apt-get install libcairo2-dev

# before build script, run autoreconf
before_script: autoreconf -i

# Default is "./configure && make && make test", but no tests yet
script: "./configure && make"

# after build script, run make install
after_success: sudo make install

# add notification email addresses
notifications:
  email:
    recipients:
      - cmujedi@west.cmu.edu
